In [1]:
#In logistic regression, values are >1 are 1 and <1 are 0.

In [2]:
#For logistic regression, apply sigmoid function on linear regression function

In [3]:
#p=1/(1+e^-y)
#ln(p/1-p)=m*x+c

In [4]:
#This curves the graph a bit

In [5]:
#Logistic Regression can only handle binary datasets

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
dataset=pd.read_csv('Social_Network_Ads.csv')
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [28]:
dataset.isnull().any().any()

False

In [29]:
df=dataset.drop('User ID',axis=1)
df

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [30]:
df['Gender'].value_counts()

Female    204
Male      196
Name: Gender, dtype: int64

In [31]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df.iloc[:,0]=lb.fit_transform(df.iloc[:,0])
df

Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

In [32]:
from scipy import stats
z=np.abs(stats.zscore(df))
z

array([[1.02020406, 1.78179743, 1.49004624, 0.74593581],
       [1.02020406, 0.25358736, 1.46068138, 0.74593581],
       [0.98019606, 1.11320552, 0.78528968, 0.74593581],
       ...,
       [0.98019606, 1.17910958, 1.46068138, 1.34059793],
       [1.02020406, 0.15807423, 1.07893824, 0.74593581],
       [0.98019606, 1.08359645, 0.99084367, 1.34059793]])

In [33]:
threshold=3
np.where(z>threshold)

(array([], dtype=int64), array([], dtype=int64))

In [34]:
x=df.iloc[:,0:3].values
x

array([[    1,    19, 19000],
       [    1,    35, 20000],
       [    0,    26, 43000],
       ...,
       [    0,    50, 20000],
       [    1,    36, 33000],
       [    0,    49, 36000]], dtype=int64)

In [35]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [16]:
#Normalization->Good practice(less variation between independent variables)

In [17]:
#Normalization using standard scalar

In [36]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[ 1.02020406, -1.78179743, -1.49004624],
       [ 1.02020406, -0.25358736, -1.46068138],
       [-0.98019606, -1.11320552, -0.78528968],
       ...,
       [-0.98019606,  1.17910958, -1.46068138],
       [ 1.02020406, -0.15807423, -1.07893824],
       [-0.98019606,  1.08359645, -0.99084367]])

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [38]:
x_train

array([[ 1.02020406,  1.94321462,  2.18056084],
       [-0.98019606,  2.03872775,  0.38930459],
       [-0.98019606, -1.30423178, -0.4329114 ],
       [-0.98019606, -1.11320552, -1.02020853],
       [-0.98019606,  1.94321462, -0.93211396],
       [-0.98019606,  0.41500455,  0.30121002],
       [-0.98019606,  0.22397829,  0.15438573],
       [ 1.02020406,  2.03872775,  1.76945285],
       [-0.98019606,  0.79705706, -0.84401939],
       [-0.98019606,  0.31949142, -0.28608712],
       [ 1.02020406,  0.41500455, -0.16862769],
       [-0.98019606, -0.0625611 ,  2.23929055],
       [-0.98019606, -1.39974491, -0.63846539],
       [ 1.02020406, -1.20871865, -1.07893824],
       [ 1.02020406, -1.30423178,  0.41866944],
       [-0.98019606, -1.01769239,  0.77104772],
       [ 1.02020406, -1.39974491, -0.19799255],
       [ 1.02020406,  0.98808332, -1.07893824],
       [ 1.02020406,  0.98808332,  0.59485858],
       [ 1.02020406,  0.41500455,  1.00596657],
       [-0.98019606,  0.60603081, -0.902

In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

In [41]:
rf=RandomForestClassifier()

In [42]:
n_estimators=[int(x) for x in np.linspace(50,1000,12)]
max_depth=[int(x) for x in np.linspace(5,30,6)]
min_samples_leaf=[1,2,5,10]
criterion=['entropy','gini']

In [43]:
random_grid = {'n_estimators':n_estimators,
                'max_depth':max_depth,
                'min_samples_leaf':min_samples_leaf,
                 'criterion':criterion
               }
random_grid

{'n_estimators': [50, 136, 222, 309, 395, 481, 568, 654, 740, 827, 913, 1000],
 'max_depth': [5, 10, 15, 20, 25, 30],
 'min_samples_leaf': [1, 2, 5, 10],
 'criterion': ['entropy', 'gini']}

In [47]:
rf_random= RandomizedSearchCV(estimator=rf,param_distributions=random_grid,scoring='accuracy', n_iter = 10, cv = 5,random_state=0)


In [48]:
rf_random.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [5, 10, 15, 20, 25, 30],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'n_estimators': [50, 136, 222, 309, 395,
                                                         481, 568, 654, 740,
                                                         827, 913, 1000]},
                   random_state=0, scoring='accuracy')

In [49]:
# https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter


In [52]:
rf_random.best_params_

{'n_estimators': 568,
 'min_samples_leaf': 5,
 'max_depth': 15,
 'criterion': 'gini'}

In [53]:
y_pred=rf_random.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [54]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.95