In [ ]:
Step 1:Importing packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
dataset=pd.read_csv('bank.csv')
dataset

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [ ]:
Step 2: Checking whether continuous values are null or not

In [4]:
dataset.isnull().any().any() #check whether they are null values

False

In [6]:
dataset.isnull().sum() #check the count of null values

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [ ]:
Step 3: Separating independent and dependent variables

In [18]:
x=dataset.iloc[:,0].values
y=dataset.iloc[:,3:5].values
z=dataset.iloc[:,8:12].values
my_independentlist=[(x,y,z)]
my_independentlist

[(array([59, 56, 41, ..., 32, 43, 34], dtype=int64),
  array([['secondary', 'no'],
         ['secondary', 'no'],
         ['secondary', 'no'],
         ...,
         ['secondary', 'no'],
         ['secondary', 'no'],
         ['secondary', 'no']], dtype=object),
  array([['unknown', 5, 'may', 1042],
         ['unknown', 5, 'may', 1467],
         ['unknown', 5, 'may', 1389],
         ...,
         ['cellular', 19, 'aug', 156],
         ['cellular', 8, 'may', 9],
         ['cellular', 9, 'jul', 628]], dtype=object))]

In [19]:
a=dataset.iloc[:,1:3].values
b=dataset.iloc[:,5:8].values
c=dataset.iloc[:,12:].values
my_dependentlist=[(a,b,c)]
my_dependentlist

[(array([['admin.', 'married'],
         ['admin.', 'married'],
         ['technician', 'married'],
         ...,
         ['technician', 'single'],
         ['technician', 'married'],
         ['technician', 'married']], dtype=object),
  array([[2343, 'yes', 'no'],
         [45, 'no', 'no'],
         [1270, 'yes', 'no'],
         ...,
         [29, 'no', 'no'],
         [0, 'no', 'yes'],
         [0, 'no', 'no']], dtype=object),
  array([[1, -1, 0, 'unknown', 'yes'],
         [1, -1, 0, 'unknown', 'yes'],
         [1, -1, 0, 'unknown', 'yes'],
         ...,
         [2, -1, 0, 'unknown', 'no'],
         [2, 172, 5, 'failure', 'no'],
         [1, -1, 0, 'unknown', 'no']], dtype=object))]

In [20]:
import sklearn

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
Separating into nominal and ordinal values

In [ ]:
Ordinal:education, marital, job, housing, loan, p outcome
Nominal:default, month, contact

In [ ]:
ct = ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)
x

In [22]:
from sklearn.preprocessing import LabelEncoder
lb= LabelEncoder()

In [27]:
x=dataset.iloc[:,1]
y=dataset.iloc[:,6]
z=dataset.iloc[:,15]
x = lb.fit_transform(x)
x

array([0, 0, 9, ..., 9, 9, 9])

In [28]:
y = lb.fit_transform(y)
y

array([1, 0, 1, ..., 0, 0, 0])

In [29]:
z = lb.fit_transform(z)
z

array([3, 3, 3, ..., 3, 0, 3])

In [33]:
new1=dataset.drop('housing',axis=1, inplace=True)
new2=dataset.drop('loan',axis=1, inplace=True)
new3=dataset.drop('day',axis=1, inplace=True)

In [34]:
dataset

age          job  marital  education default   contact month  duration  \
0       59       admin.  married  secondary      no   unknown   may      1042   
1       56       admin.  married  secondary      no   unknown   may      1467   
2       41   technician  married  secondary      no   unknown   may      1389   
3       55     services  married  secondary      no   unknown   may       579   
4       54       admin.  married   tertiary      no   unknown   may       673   
...    ...          ...      ...        ...     ...       ...   ...       ...   
11157   33  blue-collar   single    primary      no  cellular   apr       257   
11158   39     services  married  secondary      no   unknown   jun        83   
11159   32   technician   single  secondary      no  cellular   aug       156   
11160   43   technician  married  secondary      no  cellular   may         9   
11161   34   technician  married  secondary      no  cellular   jul       628   

       campaign  pdays  previous poutcome deposit  
0             1     -1         0  unknown     yes  
1             1     -1         0  unknown     yes  
2             1     -1         0  unknown     yes  
3             1     -1         0  unknown     yes  
4             2     -1         0  unknown     yes  
...         ...    ...       ...      ...     ...  
11157         1     -1         0  unknown      no  
11158         4     -1         0  unknown      no  
11159         2     -1         0  unknown      no  
11160         2    172         5  failure      no  
11161         1     -1         0  unknown      no  

[11162 rows x 13 columns]

In [36]:
y=dataset.iloc[:,4:7]
y

default   contact month
0          no   unknown   may
1          no   unknown   may
2          no   unknown   may
3          no   unknown   may
4          no   unknown   may
...       ...       ...   ...
11157      no  cellular   apr
11158      no   unknown   jun
11159      no  cellular   aug
11160      no  cellular   may
11161      no  cellular   jul

[11162 rows x 3 columns]

In [37]:
ct = ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="passthrough")
y=ct.fit_transform(y)
y

array([[1.0, 0.0, 'unknown', 'may'],
       [1.0, 0.0, 'unknown', 'may'],
       [1.0, 0.0, 'unknown', 'may'],
       ...,
       [1.0, 0.0, 'cellular', 'aug'],
       [1.0, 0.0, 'cellular', 'may'],
       [1.0, 0.0, 'cellular', 'jul']], dtype=object)

In [38]:
y=y[:,1:]
y

array([[0.0, 'unknown', 'may'],
       [0.0, 'unknown', 'may'],
       [0.0, 'unknown', 'may'],
       ...,
       [0.0, 'cellular', 'aug'],
       [0.0, 'cellular', 'may'],
       [0.0, 'cellular', 'jul']], dtype=object)

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) #independent, dependent, test size and random state

In [40]:
x_train.shape #train data

(8929,)

In [41]:
y_train.shape #train data

(8929, 3)

In [42]:
x_test.shape #test data

(2233,)

In [43]:
y_test.shape #test data

(2233, 3)